[package]
name = "montecarlo"
version = "0.1.0"
authors = ["wujinq <wujinyuan111@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14.0"
rand = "0.8.0"
ndarray-rand = "0.13.0"
nalgebra = "0.20"